# Find more information on toml format here:  https://github.com/toml-lang/toml
# ModLoader settings
modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="chunkbychunk"
version="${file.jarVersion}"
displayName="Chunk By Chunk"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
updateJSONURL="https://immortius.xyz/chunkbychunk/updates.json"
displayURL="https://immortius.xyz/chunkbychunk"
logoFile="logo.png"
credits="Sound effects from Kenny (www.kenney.nl)"
authors="Immortius"
description='''
Punch the world one chunk at a time.
This mod starts the overworld with a single chunk, but provides the tools to expand the world one chunk at a time.
'''
[[dependencies.chunkbychunk]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chunkbychunk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
