# Find more information on toml format here:  https://github.com/toml-lang/toml
# ModLoader settings
modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="chunkbychunk"
version="${file.jarVersion}"
displayName="Chunk By Chunk"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
updateJSONURL="https://immortius.xyz/chunkbychunk/updates.json"
displayURL="https://immortius.xyz/chunkbychunk"
logoFile="logo.png"
credits="Sound effects from Kenny (www.kenney.nl)"
authors="Immortius"
description='''
Punch the world one chunk at a time.

This mod provides a two new world types: "One Chunk" that generates a single chunk sky world, and "Sealed World" that seals all chunks but one in bedrock. In both cases as the bottom of the chunk is a chest that can only be opened when the chunk has been cleared, providing a block that can be placed in an empty or sealed chunk and used to spawn it. The new chunk will likewise have a chunk spawner block at the bottom. Punch a chunk, generate another, and build your world with the resources you obtain!

World setup can be customised by spawning chunks with the chunk spawner block.
'''
[[dependencies.chunkbychunk]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chunkbychunk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
